language: generic
services:
  - docker
env:
  global:
    - DOCKER_IMAGE_NAME=hettling/dockertags
    - DOCKER_TAG=${TRAVIS_TAG}
script:
  - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_TAG -t $DOCKER_IMAGE_NAME:latest ./

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $DOCKER_IMAGE_NAME:$DOCKER_TAG
  - docker push $DOCKER_IMAGE_NAME:latest
